// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmx5Hj8Sx4SY_6EsIoeSeltpmZJWj2OQA',
    appId: '1:439061157921:web:d4745cb8f2315a0803eb60',
    messagingSenderId: '439061157921',
    projectId: 'chatter-d7334',
    authDomain: 'chatter-d7334.firebaseapp.com',
    storageBucket: 'chatter-d7334.appspot.com',
    measurementId: 'G-ZEM8CE3CG5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmOsihD-jPzfVgYIUW0FnKLKckrr0uSok',
    appId: '1:439061157921:android:c908a82fb7977e4f03eb60',
    messagingSenderId: '439061157921',
    projectId: 'chatter-d7334',
    storageBucket: 'chatter-d7334.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPztnZqw5Aoy-l5yHqcwtmwuKqY6JFMVU',
    appId: '1:439061157921:ios:8d6238a6f782786e03eb60',
    messagingSenderId: '439061157921',
    projectId: 'chatter-d7334',
    storageBucket: 'chatter-d7334.appspot.com',
    androidClientId: '439061157921-0e89lc1pp8a4p3jqbdqr8n3vc6d5bmpa.apps.googleusercontent.com',
    iosClientId: '439061157921-4blkf10i5etij1a0nor8d67kt610pfvm.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPztnZqw5Aoy-l5yHqcwtmwuKqY6JFMVU',
    appId: '1:439061157921:ios:8d6238a6f782786e03eb60',
    messagingSenderId: '439061157921',
    projectId: 'chatter-d7334',
    storageBucket: 'chatter-d7334.appspot.com',
    androidClientId: '439061157921-0e89lc1pp8a4p3jqbdqr8n3vc6d5bmpa.apps.googleusercontent.com',
    iosClientId: '439061157921-4blkf10i5etij1a0nor8d67kt610pfvm.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
